<a href="https://colab.research.google.com/github/JunyuYan/Pytorch-Learning-Materials/blob/main/pytorch_official/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensors**: A specified data structure that are similiar to arrays and matrices. In pytorch, inputs, outputs of a model as well as the model's parameters are all encoded in tensor.


Tensor are similiar to Numpy's ndarray, but it can run on GPUs or other hardware accelerators. Tensors and numpy arrays can often share the same underlying memory. And tensors can also optimized for automatic differentiation.

In [25]:
import torch
import numpy as np

**Topic 1: Initializing a tensor**

(1) Directly from data:

In [26]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

(2) From a numpy array:

In [27]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

(3) From another tensor:

The new tensor retains properties (shape, dtype) of the augment tensor, unless explicitly overridden.

In [28]:
x_ones = torch.ones_like(x_data) # retains the property of x_data
print(f"Ones tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # override the dtype of x_data
print(f"Random tensor: \n {x_rand} \n")

Ones tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random tensor: 
 tensor([[0.3292, 0.5299],
        [0.4794, 0.0528]]) 



(4) With random or constant values:

Need to specify the shape of the tensor.
Genrally, there are three types: torch.rand(shape), torch.zeros(shape), torch.ones(shape)

In [29]:
shape = (2, 3, )

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")


Random Tensor: 
 tensor([[0.0905, 0.9430, 0.3222],
        [0.2662, 0.4536, 0.3326]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



**Topic 2: Attributes of a tensor:**

tensor.shape: dimensionality of a tensor

tensor.dtype: datatype of a tensor

tensor.device: device that stores the tensor

In [30]:
tensor = torch.rand(3,4)

print(f"Shape of the tensor: {tensor.shape}")
print(f"Datatype of the tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of the tensor: torch.Size([3, 4])
Datatype of the tensor: torch.float32
Device tensor is stored on: cpu


**Topic 3: Operations on tensors**

The detailed descriptions of operations on tensors are listed [here](https://pytorch.org/docs/stable/torch.html)

All operations can be executed on the GPU for acceleration.

By default, tensors are created on the CPU. We need to explicitly move tensors to GPU using to. method.

Copying large tensors across devices can be expensive in terms of time and memory!

In [31]:
# Move tensor to a GPU if the GPU is available
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

In [32]:
# Standard numpy-like indexing and slicing
tensor = torch.rand(4, 4)

print(f"Tensor: \n {tensor} \n")
print(f"First row of the tensor: {tensor[0,:]}")
print(f"First column of the tensor: {tensor[:,0]}")
print(f"Last column of the tensor: {tensor[...,-1]}")

# Assign second column to 0
tensor[:,1] = 0
print(f"Tensor after changes: \n{tensor}")

Tensor: 
 tensor([[0.9198, 0.0689, 0.6561, 0.5679],
        [0.3308, 0.3193, 0.0983, 0.3398],
        [0.6593, 0.8978, 0.1524, 0.3956],
        [0.3118, 0.2620, 0.4713, 0.7165]]) 

First row of the tensor: tensor([0.9198, 0.0689, 0.6561, 0.5679])
First column of the tensor: tensor([0.9198, 0.3308, 0.6593, 0.3118])
Last column of the tensor: tensor([0.5679, 0.3398, 0.3956, 0.7165])
Tensor after changes: 
tensor([[0.9198, 0.0000, 0.6561, 0.5679],
        [0.3308, 0.0000, 0.0983, 0.3398],
        [0.6593, 0.0000, 0.1524, 0.3956],
        [0.3118, 0.0000, 0.4713, 0.7165]])


In [33]:
# Joining tensor
# Use torch.cat to join tensors in a given dimension
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.9198, 0.0000, 0.6561, 0.5679, 0.9198, 0.0000, 0.6561, 0.5679, 0.9198,
         0.0000, 0.6561, 0.5679],
        [0.3308, 0.0000, 0.0983, 0.3398, 0.3308, 0.0000, 0.0983, 0.3398, 0.3308,
         0.0000, 0.0983, 0.3398],
        [0.6593, 0.0000, 0.1524, 0.3956, 0.6593, 0.0000, 0.1524, 0.3956, 0.6593,
         0.0000, 0.1524, 0.3956],
        [0.3118, 0.0000, 0.4713, 0.7165, 0.3118, 0.0000, 0.4713, 0.7165, 0.3118,
         0.0000, 0.4713, 0.7165]])


In [34]:
# Arithmetic operations
# tensor.T: transpose operation
# y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

# Element-wise product
# z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
z3 = torch.mul(tensor, tensor, out=z3)


In [35]:
# Single-element tensors
# For single-element tensor, we can use item() to aggregate all values of a tensor into a numerical value

agg = tensor.sum()
agg_item = agg.item()
print(f"agg = : {agg}")
print(f"agg_item = : {agg_item}, datatype is: {type(agg_item)}")

agg = : 5.619694709777832
agg_item = : 5.619694709777832, datatype is: <class 'float'>


In [36]:
# Inplace operations: stores the result into operand; denoted by _; save more memory but problematic when computing derivatives
print(f"Original tensor is: \n {tensor} \n")
tensor.add_(1)
print(f"Tensor after the in-place operation: \n {tensor} \n")

Original tensor is: 
 tensor([[0.9198, 0.0000, 0.6561, 0.5679],
        [0.3308, 0.0000, 0.0983, 0.3398],
        [0.6593, 0.0000, 0.1524, 0.3956],
        [0.3118, 0.0000, 0.4713, 0.7165]]) 

Tensor after the in-place operation: 
 tensor([[1.9198, 1.0000, 1.6561, 1.5679],
        [1.3308, 1.0000, 1.0983, 1.3398],
        [1.6593, 1.0000, 1.1524, 1.3956],
        [1.3118, 1.0000, 1.4713, 1.7165]]) 



**Topic 4: Bridge with Numpy**

Tensors on the CPU and numpy arrays can share their underlying memory locations, and change one will change another one.


Tensor to numpy array:

t.numpy()

In [37]:
t = torch.ones(5)
print(f"tensor t is: {t}")
n = t.numpy()
print(f"numpy n is {n}")

tensor t is: tensor([1., 1., 1., 1., 1.])
numpy n is [1. 1. 1. 1. 1.]


In [38]:
# Change one will reflect in another one
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


Numpy array to tensor:

torch.from_numpy()

In [39]:
n = np.ones(5)
t = torch.from_numpy(n)

print(f"numpy n is: {n}")
print(f"tensor t is: {t}")

numpy n is: [1. 1. 1. 1. 1.]
tensor t is: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [40]:
np.add(n, 1, out=n)

print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
